version: 0.2


phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo test 

  build:
    commands:
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - export PATH=$PWD/:$PATH
      - apt-get -y install jq
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --role-arn arn:aws:iam::987654321:role/EksCodeBuildkubectlRole
      - kubectl get nodes 
