kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc-1b
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - eu-west-1b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim-1b
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-1b
  resources:
    requests:
      storage: 4Gi
---
