apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: producao
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/security-groups: sg-xxxxxxx,sg-yyyyyy
  labels:
    run: nginx
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: nginx
              servicePort: 80
